POST http://localhost:3030/contract-po
Content-Type: application/json

{
    "PoNumber": "",
    "Flag": "",
    "DocType": "ZSES",
    "Project": "M20030000",
    "Vendor": "20000064",
    "PurchOrg": "1000",
    "PurchDoc": "",
    "Message": "",
    "PurGroup": "SRV",
    "CompCode": "1000",
    "DocDate": null,
    "VperStart": null,
    "VperEnd": null,
    "Status": "",
    "DeleteInd": "",
    "ContractDesc": "test",
    "LongDesc": "test",
    "Currency": "EGP",
    "MeasMethod": "REMS",
    "ConstructionType": "T",
    "RefContract": "",
    "CreationDate": null,
    "ValidFrom": null,
    "ValidTo": null,
    "SigninDate": null,
    "RevisedValidTo": null,
    "IndexMonth": "",
    "Consultant": "",
    "ConsultantName": "",
    "Ss": "",
    "Ir": "",
    "SuperiorWbs": "",
    "CreationType": "O",
    "MarkUp": "0.0",
    "VendorName": "سى ان اس",
    "POHeaderToPOItem": [],
    "POHeaderToPOBuildingNav": [],
    "AttachmentSet": [],
    "EstimatedContractValue": "0.00",
    "OriginalContractValue": "0.00",
    "TotalContractValue": "0.00",
    "VariationOrderValue": "0.00",
    "AddendumValue": "0.00",
    "RevisedContractValue": "0.00",
    "SerType": "",
    "ContractPONoteNav": {}

}