POST http://localhost:3030/contract/po-header
Content-Type: application/json

{
    "PoNumber": "",
    "Flag": "",
    "DocType": "ZSES",
    "Project": "S25010000",
    "Vendor": "20000064",
    "PurchOrg": "1000",
    "PurchDoc": "",
    "Message": "",
    "PurGroup": "SRV",
    "CompCode": "1000",
    "DocDate": "2023-10-01",
    "VperStart": "2023-10-01",
    "VperEnd": "2023-10-01",
    "Status": "",
    "DeleteInd": "",
    "ContractDesc": "Hassan Elsherbiny",
    "LongDesc": "Hassan Elsherbiny",
    "Currency": "EGP",
    "MeasMethod": "REMS",
    "ConstructionType": "T",
    "RefContract": "",
    "CreationDate": "2023-10-01",
    "ValidFrom": "2023-10-01",
    "ValidTo": "2023-10-01",
    "SigninDate": "2023-10-01",
    "RevisedValidTo": "2023-10-01",
    "IndexMonth": "",
    "Consultant": "",
    "ConsultantName": "",
    "Ss": "",
    "Ir": "",
    "SuperiorWbs": "",
    "CreationType": "O",
    "MarkUp": "0.0",
    "VendorName": "سى ان اس",
    "POHeaderToPOItem": [],
    "POHeaderToPOBuildingNav": [],
    "AttachmentSet": [],
    "EstimatedContractValue": "0.00",
    "OriginalContractValue": "0.00",
    "TotalContractValue": "0.00",
    "VariationOrderValue": "0.00",
    "AddendumValue": "0.00",
    "RevisedContractValue": "0.00",
    "SerType": "0001",
    "ContractPONoteNav": {}
}
