export class CreateContractTermsDto {
  ContractNo: any;
  Version: number;
  DeliveryDate?: Date;
  Status?: string;
  CreatedOn?: Date;
  CreatedBy?: string;
  LastChangedOn?: Date;
  LastChangedBy?: string;
  ShipInvoicePerc?: number;
  CompCode?: string;
  PaymentTermsCode?: string;
  PaymentTermsDays?: number;
  VariationOriginalPer?: number;
  InflationOriginalPer?: number;
  RemeasuredOriginalPer?: number;
  VariationRevisitedPer?: number;
  InflationRevisitedPer?: number;
  RemeasuredRevisitedPer?: number;
  ContractType?: string;
  ProfitCenter?: string;
  ProfitCenterName?: string;
  PriceInclusive?: string;
  VatCode?: string;
  TaxCode?: string;
  TaxAmount?: number;
  BaseAmount?: number;
  Overviewstatus?: string;
}
