import { ContractPOItem } from '../entities/contractPOItem.entity';

export function mapPoItemData(req: any): Partial<ContractPOItem> {
  return {
    PoItem: req.PoItem,
    iuidRelevant: req.IuidRelevant,
    prItem: req.PrItem,
    priceUnit: req.PriceUnit,
    srvType: req.SrvType,
    amount: req.Amount,
    provisionRate: req.ProvisionRate,
    boqStxt: req.BoqStxt,
    network: req.Network,
    activityNumber: req.ActivityNumber,
    currency: req.Currency,
    buildingno: req.Buildingno,
    contractualIndicator: req.ContractualIndicator,
    matdesc: req.Matdesc,
    serviceType: req.ServiceType,
    srvStatus: req.SrvStatus,
    txt: req.Txt,
    boqLtxt: req.BoqLtxt,
    changeIndicator: req.ChangeIndicator,
    subBoq: req.SubBoq,
    subboqStxt: req.SubboqStxt,
    variationOrder: req.VariationOrder,
    flag: req.Flag,
    subboqLtxt: req.SubboqLtxt,
    ovfTol: req.OvfTol,
    project: req.Project,
    servicedesc: req.Servicedesc,
    srvNo: req.Serviceno,
    longText: req.LongText,
    purchDoc: req.PurchDoc,
    boq: req.Boq,
    deleteInd: req.DeleteInd,
    plant: req.Plant,
    matlGroup: req.MatlGroup,
    qty: req.Qty,
    poUnit: req.PoUnit,
    itemCat: req.ItemCat,
    acctasscat: req.Acctasscat,
    shortText: req.ShortText,
    serviceno: req.Serviceno,
    baseUom: req.BaseUom,
    wbsElement: req.WbsElement,
    noLimit: req.NoLimit,
    deliveryDate: req.DeliveryDate,
    poHeader: req.PoHeader,
    poHeaderId: req.PoHeader, // Link by object reference
  };
}
